import { Router } from "express";
import { register, login, logout, refresh, requestOtp, verifyOtp, resetPassword, googleAuth, appleAuth, deleteAccount, setRole } from "../controllers/auth.controller";
import { protect } from "../middleware/auth.middleware";
const router = Router();
router.post("/register", register);
router.post("/login", login);
router.post("/logout", logout);
router.post("/refresh", refresh);
router.post("/request-otp", requestOtp);
router.post("/verify-otp", verifyOtp);
router.post("/reset-password", resetPassword);
router.post("/google", googleAuth);
router.post("/apple", appleAuth);
router.delete("/account", protect, deleteAccount);
router.patch("/role", protect, setRole);
export default router;
